# Generated by Django 4.2.5 on 2024-02-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgfinder_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='contact',
            field=models.IntegerField(max_length=11),
        ),
    ]
