# Generated by Django 4.2.5 on 2024-03-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgfinder_admin', '0002_alter_user_info_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='b_price',
            field=models.IntegerField(default=-1, max_length=50),
            preserve_default=False,
        ),
    ]
