# Generated by Django 4.2.5 on 2024-03-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgfinder_admin', '0003_booking_b_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pg_room_gallary',
            name='image_patten',
            field=models.CharField(max_length=20000),
        ),
    ]
