# Generated by Django 4.2.5 on 2024-03-22 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgfinder_admin', '0004_alter_pg_room_gallary_image_patten'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='b_price',
        ),
    ]
