# Generated by Django 4.2.5 on 2024-03-27 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgfinder_admin', '0005_remove_booking_b_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pg_owner',
            name='cover_image',
        ),
    ]
